### ISSUE TITLE
Improve CTQ notifier

### ISSUE THREAD

**Issue by chrisklus** [phetsims/aqua#152]
This issue is for the remaining work to do for CTQ notifier:

- [x] ~convert QuickServer.js to TypeScript~ no-op, QuickServer is node code
- [x] better commenting and small cleanup in QuickServer - completed in https://github.com/phetsims/aqua/issues/166
- [ ] investigate to see if there is a way to wait for a complete push to multiple repos before running a CTQ loop that sometimes reports false positives
- [x] investigate if there is a better way to handle a high load of errors, as described by @zepumph in https://github.com/phetsims/aqua/issues/141#issuecomment-1156810642

**Comment by chrisklus** [comment]
@samreid reported in https://github.com/phetsims/chipper/issues/1269#issuecomment-1179428500 an idea for a better way to notify CTQ that a set of pushes is complete! This would address the third checkbox in the list above.

**Comment by samreid** [comment]
The same idea could be leveraged for the full CT like so:

* The push script notifies that it is about to push certain repos. `fetch('http://bayes.colorado.edu/ct/prepush?repos=sim1,sim2,common1)`
* The push script pushes the repos
* The push script notifies that it has pushed the repos. `fetch('http://bayes.colorado.edu/ct/postpush?repos=sim1,sim2,common1)`

Then CT and CTQ can identify whether they are in a consistent state if they aren't waiting for any prepushes to finish.  Or maybe we would just use a random token like `start=n2th1nth23n12th3n` and `end=n2th1nth23n12th3n`.  CT could give up if it doesn't receive the end for a start within N minutes.

**Comment by pixelzoom** [comment]
In Slack#continuous-testing, I suggested something else:

It seems like many (most?) of the CTQ false positives (aka :dodo:) occur when pushing to multiple repos.  I don’t know how CT knows when to pull repos. But I suspect it notices that a repo has changed, then pulls only that repo. Could this problem be resolved (or reduced in frequency) by introducing a slight delay after CT notices any repo change, then doing a pull-all?

**Comment by pixelzoom** [comment]
In Slack#continuous-testing, @zepumph said:

> The logic is here, it would be simple enough to instead wait 20 seconds before running it. https://github.com/phetsims/aqua/blob/a2dcc1f69f09cd5d3b48845c6574bf4a89b54cfe/js/server/QuickServer.js#L111-L121

**Comment by zepumph** [comment]
@chrisklus, https://github.com/phetsims/aqua/commit/1de7fdf7b10ef32d41b96404201de183b37c6739 was causing a bunch of problems because it was kicking off infinite numbers of setTimeout calls and running out of memory on the javascript heap. We need to synchronously pause execution of the while loop if we find a staleRepo. Let's try this one.

**Comment by zepumph** [comment]
Working on this today as part of https://github.com/phetsims/aqua/issues/166

**Comment by chrisklus** [comment]
@zepumph do you think we can close this issue? Or wait another month or so to see if item 3 in https://github.com/phetsims/aqua/issues/152#issue-1295965086 needs more work?

**Comment by zepumph** [comment]
I was just thinking that! I do not think any more is needed here. Thanks
