### ISSUE TITLE
EPIC: install and configure {{insert name here}} 

### ISSUE THREAD

**Issue by mattpen** [phetsims/aqua#161]
The dedicated CT replacement has been delivered to CU and is being transported to a data center.  

OIT will likely complete these tasks:

- [ ] Install the OS 
- [ ] Setup a single user with sudo privileges so we can logon
- [ ] Configure the networking 
- [ ] Setup the RAID configuration

Questions:

- [ ] Which OS do we want? (MP: I recommend [RHEL 9](https://access.redhat.com/support/policy/updates/errata) but there are lots of other options).
- [ ] What is the name of the server?
- [ ] What is it's IP address?

To do list:

- [ ] Configure IDRAC
- [ ] Configure AD integration (identikey login), including sudo access
- [ ]  Setup machine user for CT
- [ ] Install node/npm
- [ ] Install aqua/CT service and dependencies
- [ ] [Register RHEL8 software](https://oit.colorado.edu/services/consulting-professional-services/systems-engineering/red-hat)
- [ ] Configure dnf to automatically install system updates
- [ ] [Set timezone](https://linuxconfig.org/redhat-8-change-timezone) to Denver (MST/MDT)
- [ ] ...?

A lot of these tasks have some of the steps documented in the setup issue for phet-server2: https://github.com/phetsims/website/issues/1271

**Comment by jonathanolson** [comment]
For a name, I'd prefer something fairly easy to type!
