### ISSUE TITLE
Address review/discussion feedback for automated test harnesses

### ISSUE THREAD

**Issue by samreid** [phetsims/aqua#30]
In today's discussion of #29 we recommended this additional work:

- [ ] dot/kite/axon test configs have extra stuff => or just use one config file with different deps, see https://github.com/phetsims/chipper/issues/638

- [x] move docs somewhere.  grunt --help should point to the docs

- [x] maybe can get rid of these ( see https://github.com/phetsims/aqua/issues/31)
    // if ( !window.assert ) {
    //   assert.expect( 3 ); // TODO: this is a hack to suppress the "expected 0 tests but 5 were run" error.
    // }

- [x] can get rid of the 0s as well. (see https://github.com/phetsims/aqua/issues/31)

**Comment by samreid** [comment]
I added docs in the preceding commits.  The chipper 2.0 `grunt --help` points to https://github.com/phetsims/aqua/blob/master/docs/adding-tests.md and it's ready for review.

**Comment by samreid** [comment]
`assert.expect` is basically taken care of, last loose ends for that are tracked in https://github.com/phetsims/scenery/issues/720 . I'll check them off of this list.

**Comment by samreid** [comment]
All checkboxes complete or moved to other issues, closing.
